const image =
{
    experimindlabs_logo: require('./assets/logo.png'),
    heroimg: require('./assets/Experimindlabs-HeroImg.webp'),
    who_we_are_1: require('./assets/About-ExperimindLabs-1st-pic.webp'),
    who_we_are_2: require('./assets/About-ExperimindLabs-2nd-pic.webp'),
    arrow: require('./assets/arrow-right-circle.png'),
    shiksha: require('./assets/Shiksha.webp'),
    psl: require('./assets/Experimind-PSL.webp'),
    prastuti: require('./assets/Experimind-Prastuti.webp'),
    geomagic: require('./assets/Experimind_GeoMagic.webp'),
    anubhav: require('./assets/Experimind-Anubhav-Kit.webp'),
    aicnitte: require('./assets/AIC_nitte_Logo.webp'),
    aim: require('./assets/AIM_Logo.webp'),
    ngi: require('./assets/NGI_Logo.webp'),
    rv: require('./assets/RVU_Logo.webp'),
    nitte: require('./assets/Nitte_Logo.webp'),
    ssrvm: require('./assets/Ravishankar_Logo.webp'),
    sbc: require('./assets/SBC_Logo.webp'),
    yfs: require('./assets/YFS_Logo.webp'),
    whychooseus: require('./assets/Experimindlabs-kids-studing.webp'),
    meeting: require('./assets/Experimindlabs-meeting.webp'),
    vision_icons: require('./assets/file-detail.png'),
    mission_icons: require('./assets/briefcase-alt-2.png'),
    values_icons: require('./assets/community.png'),
}
export default image;