const image =
{
    heroimg: require('./assets/Heroimg.webp'),
    who_we_are_1: require('./assets/About-ExperimindLabs-1st-pic.webp'),
    who_we_are_2: require('./assets/About-ExperimindLabs-2nd-pic.webp'),
    arrow: require('./assets/arrow-right-circle.png'),
    shiksha: require('./assets/Experimind-labs-Robot-Shiksha.webp'),
    psl: require('./assets/Experimind_PSL.webp'),
    prastuti: require('./assets/Experimind-Prastuti.webp'),
    geomagic: require('./assets/Experimind_GeoMagic.webp'),
    anubhav: require('./assets/Experimind-Anubhav-Kit.webp'),
    aicnitte: require('./assets/AIC_nitte_Logo.webp'),
    aim: require('./assets/AIM_Logo.webp'),
    ngi: require('./assets/NGI_Logo.webp'),
    rv: require('./assets/RVU_Logo.webp'),
    nitte: require('./assets/Nitte_Logo.webp'),
    ssrvm: require('./assets/Ravishankar_Logo.webp'),
    sbc: require('./assets/SBC_Logo.webp'),
    yfs: require('./assets/YFS_Logo.webp'),
    whychooseus: require('./assets/Experimindlabs-kids-studing.webp'),
    meeting: require('./assets/Experimindlabs-meeting.webp'),
    vision_icons: require('./assets/file-detail.png'),
    mission_icons: require('./assets/briefcase-alt-2.png'),
    values_icons: require('./assets/community.png'),
    meeting2: require('./assets/Experimind-labs-Meeting-Room.webp'),
    insta: require('./assets/instagram.png'),
    Twitter: require('./assets/twitter-x.png'),
    linkedin: require('./assets/linkedin.png'),
    youtube: require('./assets/youtube.png'),
    ceo: require('./assets/Akshay-Mashelkar.webp'),
    director: require("./assets/Latha-Bhandari.webp"),
    cto: require('./assets/Adarsh-Devadiga.webp'),
    techinical_engineer: require('./assets/Anand-J.webp'),
    accountant: require('./assets/Shruthi.webp'),
    intern1: require('./assets/Sapekcha-Bhandari.webp'),
    intern2: require('./assets/Kavan-Shetty.webp'),
    production: require('./assets/Sagar-Shanbhogue.webp'),
    intern4: require('./assets/Harish-Vishwanath-Bhat.webp'),
    intern5: require('./assets/Sandesh-Shripad-hegde.webp'),
    intern6: require('./assets/Shramanth-P-Acharya.webp'),
    intern7: require('./assets/Manish-Poojary.webp'),
    intern3: require('./assets/Sharath-Dinesh.webp'),
}
export default image;